### ISSUE TITLE
[BUG] Paladin rune abilities missing the "is ability" flag and not proccing wild strikes

### ISSUE THREAD

**Issue by CharWS** [CharWS/season-of-discovery-bugs#4] opened 2024-01-16 22:16 UTC
#### 1.1. Description
The new paladin rune attacks crusader strike and divine storm do not have the "is ability" flag and as such do not proc wild strikes
  #### 1.2. How to Reproduce
           1. find a druid, make sure they have wild strikes
           2. have the druid enter cat/bear form within range so that the paladin has the weapon imbue
           3. engrave crusader strike or divine storm runes
           4. approach an enemy perpendicular to them such that you can hit them with special attacks but not auto attacks
           5. use crusader strike/divine storm many times
           6. note the lack of wild strikes procs

#### 2.1. Description
Crusader strike and Divine Storm are both weapon attacks scaling from weapon damage as such it's expected that they would be abilities and function identical to other such abilities which do proc wild strikes extra attacks

**Comment by Surveillant0** [comment] 2024-01-30 05:53
Based on consulting with a few other people about this bug, I don't actually think it needed to add the "is ability" flag.
Forgive me if this is wrong, but I have been told that to fix this:

Seals should only proc on the following flag:
PROC_FLAG_DONE_MELEE_AUTO_ATTACK

While Wild Strikes should proc on both of the following proc flags:
PROC_FLAG_DONE_MELEE_AUTO_ATTACK
PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS

Their intent is to prevent Seals from getting procs from CS / DS, based on what was said on the Countdown to Classic podcast, and that is why they did not fix Wild Strikes, as they said it will cause seals to proc from those abilities. However, I am told that this is not really a limitation, and if the proc flags are changed like so, the issue is fixed without creating seal procs on CS / DS.

**Closed** 2024-02-06 23:55 UTC
Labels: fixed, Paladin
